# Generated by Django 4.0.5 on 2022-06-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderinfo',
            unique_together={('order', 'product')},
        ),
    ]
